sudo: required
services:
  - docker
before_install:
  - docker build -t alexwong/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run alexwong/react-test npm run test -- --coverage   

after_success:
  - docker build -t lexwong/multi-client ./client 
  - docker build -t lexwong/multi-nginx ./nginx
  - docker build -t lexwong/multi-server ./server
  - docker build -t lexwong/multi-worker ./worker
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push to docker hub
  - docker tag  lexwong/multi-client lexwong/multi-client
  - docker push lexwong/multi-client
  #- docker push alexwong/multi-nginx:1.0.0
  #- docker push alexwong/multi-server:1.0.0
  #- docker push alexwong/multi-worker:1.0.0